### PR TITLE
feat: frontend backend and ui improvements

### PR DESCRIPTION
**Pull request by AyushSehrawat**
# Pull Request Check List

Resolves: #issue-number-here

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

### CODE REVIEW

**Comment by dreulavelle** [comment]
dont forget to merge main into this as I just pushed an update (including api changes) like 10 mins ago

**Comment by AyushSehrawat** [comment]
> dont forget to merge main into this as I just pushed an update (including api changes) like 10 mins ago

Yeah already done, just ping me in future

**Comment by dreulavelle** [comment]
I tweaked 2 files on frontend to add checkbox for the `Use Webhook` for Overseerr

**Review by dreulavelle — APPROVED** [review]
I'll approve it for now for you, so just push whenever your ready with it

**Comment by AyushSehrawat** [comment]
> I tweaked 2 files on frontend to add checkbox for the `Use Webhook` for Overseerr

Just why merge conflicts on my end?

**Comment by dreulavelle** [comment]
> > I tweaked 2 files on frontend to add checkbox for the `Use Webhook` for Overseerr
> 
> Just why merge conflicts on my end?

I didn't. It's gh

**Pull request merged**
