### PR TITLE
feat: database migrations, so long db resets

### PR DESCRIPTION
**Pull request by Gaisberg**
# Pull Request Check List

Resolves: #issue-number-here

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

### CODE REVIEW

**Comment by iPromKnight** [comment]
Looks good man - great work
We can prob get rid of that README file

**Comment by DamnDam** [comment]
@dreulavelle 
I'm having a crash loop now on startup when upgrading from 0.16.2

riven  | alembic.util.exc.CommandError: Can't locate revision identified by '97cbe84f0c18'
riven  | 24-11-05 19:12:00 |  CRITICAL  | main.<module> - Server has been stopped

**Comment by DamnDam** [comment]
For reference when running in compose and crashlooping as I was:
 
`docker compose run --entrypoint python riven /riven/src/main.py --hard_reset_db_pre_migration`

**Comment by filiptrplan** [comment]
> docker compose run --entrypoint python riven /riven/src/main.py --hard_reset_db_pre_migration

This should be really added to release notes! @dreulavelle

**Pull request merged**
