### PR TITLE
feat: add optional memory limiter

### PR DESCRIPTION
**Pull request by dreulavelle**
# Pull Request Check List

Resolves: #issue-number-here

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

### CODE REVIEW

**Comment by dreulavelle** [comment]
I know we want to move to id handling, but would this be useful to have as well? @Gaisberg @filiptrplan

**Comment by davidemarcoli** [comment]
@dreulavelle Would be useful as a fallback for systems that kill the containers/pods after they reach a limit. Elfhosted for example.
If the limit never gets reached, even better!

**Comment by filiptrplan** [comment]
> I know we want to move to id handling, but would this be useful to have as well? @Gaisberg @filiptrplan

Sorry for the late reply. I think it is a nice addition for low-end systems even if we move to IDs. It would prevent them from going unresponsive when dealing with large libraries.

As far as I understand this is just preventing events from being added if there are too many in queue?

**Comment by davidemarcoli** [comment]
Shouldn't this be moved to the function that actually adds the items to the queue, not just retry library? Or do new items also go through there?

**Comment by dreulavelle** [comment]
We shouldnt need this anymore

**Pull request closed without merging**
