### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by centerionware**
# Pull Request Check List

Resolves: #issue-number-here

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

### CODE REVIEW

**Comment by centerionware** [comment]
Need to add one more patch then will re-open

**Comment by centerionware** [comment]
sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <Episode at 0x7f2f57de4b10> is not bound to a Session; lazy load operation of attribute 'parent' cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
still happening, investigating.

**Comment by dreulavelle** [comment]
you can set the PR to `draft` so that it doesnt get accidentally merged by one of us

**Comment by centerionware** [comment]
I believe this is ready to go to the branch.

**Pull request merged**
